spring:
  profiles:
    active: dev
server:
  port: 8081
mybatis:
    mapper-locations: classpath:mappers/*.xml

logging:
  path: /log/payment/
  config: classpath:config/logback.xml
  level:
    org:
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG